### PR TITLE
update nginx config

### PR DESCRIPTION
**Pull request by naviat**
Update Nginx configuration to serve static maintenance page

### CODE REVIEW

**Comment by naviat** [comment]
For #2

**Review by etienne-napoleone — CHANGES_REQUESTED** [review]
All path should proxy the maintenance page otherwise people will just get an ugly nginx 404

**Comment by naviat** [comment]
updated.
close #4

**Review by etienne-napoleone — APPROVED** [review]
Perfect thanks!
Cool to have the right favicon too :+1:

**Pull request merged**
